const DISPATCH_LOAD = 'DISPATCH_LOAD'
const DISPATCH_ERROR = 'DISPATCH_ERROR'
const DISPATCH_BOOK_ITEMS = 'DISPATCH_FETCH'

const DISPATCH_CATEGORY_LOAD = 'DISPATCH_CATEGORY_LOAD'
const DISPATCH_CATEGORY_ITEM = 'DISPATCH_CATEGORY_ITEM'
const DISPATCH_CATEGORY_ERROR = 'DISPATCH_CATEGORY_ERROR'

const DISPATCH_LASTBOOKS_LOAD = 'DISPATCH_LASTBOOKS_LOAD'
const DISPATCH_LASTBOOKS_ITEM = 'DISPATCH_LASTBOOKS_ITEM'
const DISPATCH_LASTBOOKS_ERROR = 'DISPATCH_LASTBOOKS_ERROR'

const DISPATCH_CATBOOKS_LOAD = 'DISPATCH_CATBOOKS_LOAD'
const DISPATCH_CATBOOKS_ITEM = 'DISPATCH_CATBOOKS_ITEM'
const DISPATCH_CATBOOKS_ERROR = 'DISPATCH_CATBOOKS_ERROR'

export {
  DISPATCH_BOOK_ITEMS,
  DISPATCH_LOAD,
  DISPATCH_ERROR,
  DISPATCH_CATEGORY_LOAD,
  DISPATCH_CATEGORY_ITEM,
  DISPATCH_CATEGORY_ERROR,
  DISPATCH_LASTBOOKS_LOAD,
  DISPATCH_LASTBOOKS_ITEM,
  DISPATCH_LASTBOOKS_ERROR,
  DISPATCH_CATBOOKS_LOAD,
  DISPATCH_CATBOOKS_ITEM,
  DISPATCH_CATBOOKS_ERROR,
}
